fieldLayouts:
  eac00c81-c9a7-4d89-91e2-2a16c89ea38a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2efb78f7-165b-4274-969b-f420056d23f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5b25a878-0cda-48df-80b8-bf24b1ee8410 # Sample Text Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15d79055-ff14-4de0-907e-066f3434033d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90d79f86-2a09-4097-9fcd-c3a71eef4123
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 4251a17a-0f5d-44d0-8ede-5ca5ac9342a3 # News
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
