name: PHPStan
on:
  push:
jobs:
  phpstan:
    env:
      WEBROOT: ${{ github.workspace }}
      CRAFT_APP_ID: CraftCMS--886266cf-706e-4a9f-854c-45362102e8ef
      CRAFT_ENVIRONMENT: production
      CRAFT_SECURITY_KEY: tmp
      CRAFT_DB_DRIVER: mysql
      CRAFT_DB_SERVER: 127.0.0.1
      CRAFT_DB_PORT: 3306
      CRAFT_DB_DATABASE: phpstan
      CRAFT_DB_USER: root
      CRAFT_DB_PASSWORD: root
      CRAFT_DB_TABLE_PREFIX: craft_
      CRAFT_CP_TRIGGER: admin
      CRAFT_QUEUE_DRIVER: sync
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: phpstan
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Composer cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      - name: Copy over .env
        run: cp .env.example.dev .env
      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-ansi
        if: steps.composer-cache.outputs.cache-hit != 'true'
      - name: DB cache
        id: db-cache
        uses: actions/cache@v3
        with:
          path: dump.sql
          key: ${{ runner.os }}-db-${{ hashFiles('config/project/project.yaml', 'migrations/*.php') }}
      - name: Wait for MySQL
        run: until mysqladmin ping -h 127.0.0.1 -u root -proot; do sleep 1; done
      - name: Restore database
        if: steps.db-cache.outputs.cache-hit == 'true'
        run: mysql -h 127.0.0.1 -u root -proot phpstan < dump.sql
      - name: Install Craft
        if: steps.db-cache.outputs.cache-hit != 'true'
        run: |
          ./craft install --interactive=0 --username=michael@bluth.com --email=michael@bluth.com --password=secret --siteName="PHPStan Test" --siteUrl=http://localhost:8080 --language=en-US
          ./craft migrate/all --interactive=0
          mysqldump -h 127.0.0.1 -u root -proot phpstan > dump.sql
      - name: Run PHPStan
        run: ./vendor/bin/phpstan --memory-limit=-1 analyse
